from . import (
    funcionarios,
    ferias,
    feriados,
    agenda,
    avisos,
    solicitacoes,
    documentos,
    cooperativa_ideias,
    tribunais,
    base_conhecimento,
    manual_interno,
    notificacoes,
    onboarding,
)

all_routers = [
    funcionarios.router,
    ferias.router,
    feriados.router,
    agenda.router,
    avisos.router,
    solicitacoes.router,
    documentos.router,
    cooperativa_ideias.router,
    tribunais.router,
    base_conhecimento.router,
    manual_interno.router,
    notificacoes.router,
    onboarding.router,
]
